version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - ./:/api
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: