version: '3'
services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/api/
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
      - ../data/configdb:/data/configdb
volumes:
  mongodb: